#+HUGO_BASE_DIR: .
#+HUGO_SECTION: posts/
#+options: author:nil

* Blog

** Will's new blog                                :emacs:meta:
:PROPERTIES:
:EXPORT_FILE_NAME: first-post
:END:
I have decided to start writing a technical blog, hosted on github pages.  It will be focused on python, emacs, and astrophysics.

This all started in a roundabout way after I was looking into bi-directional import/export between Things 3 and Emacs org-mode.  That led me to looking at Karl Voit's [[https://github.com/novoid/orgformat][orgformat]] python library, which in turn led to his [[https://github.com/novoid/lazyblorg][lazyblorg]] blogging environment for org-mode.  I had always meant to try and start a blog, making use of all the reams of material that I write in my org-mode notes, but had never got round to it.  This has finally pushed me into making the leap. 

However, I quickly realised that lazyblorg was not necessarily the best approach: there are [[https://orgmode.org/worg/org-blog-wiki.html][many other]] options for blogging from emacs org-mode.  It looks like ox-hugo is the most feature-filled and widely used, and maybe I will even get to learn the Go language.  I guess I am not quite lazy enough for lazyblorg. 
